/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package outlay3.code;

/**
 *
 * @author core i5
 */
public class HalamanUtama extends javax.swing.JFrame {
    
    HalamanUtamaControl control = new HalamanUtamaControl();
    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
        kategori_button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sidebar_button = new javax.swing.JButton();
        kategori_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Diagram = new javax.swing.JMenu();
        Angka = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HalamanUtama");

        sidebar_button.setText("SideBar");
        sidebar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebar_buttonActionPerformed(evt);
            }
        });

        kategori_button.setText("Kategori");
        kategori_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategori_buttonActionPerformed(evt);
            }
        });

        Diagram.setText("Diagram");
        Diagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiagramMouseClicked(evt);
            }
        });
        jMenuBar1.add(Diagram);

        Angka.setText("0");
        Angka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AngkaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Angka);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebar_button)
                    .addComponent(kategori_button))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(sidebar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kategori_button)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiagramMouseClicked
        // TODO add your handling code here:
        control.openHalamanPengeluaran();
        this.setVisible(false);
    }//GEN-LAST:event_DiagramMouseClicked

    private void AngkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AngkaMouseClicked
        // TODO add your handling code here:
        control.openFormPengeluaran();
        this.setVisible(false);
    }//GEN-LAST:event_AngkaMouseClicked

    private void kategori_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategori_buttonActionPerformed
        // TODO add your handling code here:
        control.openHalamanKategori();
        this.setVisible(false);
    }//GEN-LAST:event_kategori_buttonActionPerformed

    private void sidebar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebar_buttonActionPerformed
        // TODO add your handling code here:
        if(kategori_button.isVisible() == false){
            kategori_button.setVisible(true);
        }
        else{
            kategori_button.setVisible(false);
        }
    }//GEN-LAST:event_sidebar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Angka;
    private javax.swing.JMenu Diagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton kategori_button;
    private javax.swing.JButton sidebar_button;
    // End of variables declaration//GEN-END:variables
}
